import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      admin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      admin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      description: 'high quality product',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
      description: 'high quality product',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'high quality product',
    },
    {
      name: 'Best Pants',
      slug: 'best-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 5,
      description: 'high quality product',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 100,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 4,
      countInStock: 7,
      description: 'high quality product',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 110,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 6,
      countInStock: 0,
      description: 'high quality product',
    },
  ],
};

export default data;
